{% set name = "multimethod" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b315d6c965a797899a699913cdc391ded51dca22db5d11bda3399ce24ffed76

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - multimethod

about:
  home: https://github.com/coady/multimethod
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Multiple argument dispatching.
  doc_url: https://multimethod.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - albop
